##### ProdutosCatalogo
GET http://localhost:8080/intellipac/api/produtosCatalogo
Accept: application/json

###
POST http://localhost:8080/intellipac/api/produtosCatalogo
Content-Type: application/json

{
  "nome": "Produto1234",
  "fabricanteUsername": "Apple",
  "embalagensACriar": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ],
  "peso": 3
}

###
PUT http://localhost:8080/intellipac/api/produtosCatalogo/2
Content-Type: application/json

{
  "nome": "Produto (PUT)",
  "fabricanteUsername": "Apple",
  "embalagensACriar": [
    {
      "id": 2
    },
    {
      "id": 3
    }
  ],
  "peso": 31
}

###
DELETE http://localhost:8080/intellipac/api/produtosCatalogo/2
Accept: application/json

##### Detalhes de um produtoCatalogo
GET http://localhost:8080/intellipac/api/produtosCatalogo/2
Accept: application/json

##### Produtos Fisicos

GET http://localhost:8080/intellipac/api/produtosFisicos
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJjbyIsImlhdCI6MTcwNTYyNjMzMSwiZXhwIjoxNzA1NjI5OTMxfQ.lcdjIuE_Vj0HAU5zz-RY2arTrDPU3FyAfDLm2HZvsJM6zHJZtPEvLsGHEpdux07H

###
POST http://localhost:8080/intellipac/api/produtosFisicos
Content-Type: application/json

{
  "nome": "Produto1Fisico (POST)",
  "fabricanteUsername": "Apple",
  "produtoCatalogoId": 1,
  "encomendaId": 1
}

###
PUT http://localhost:8080/intellipac/api/produtosFisicos/3
Content-Type: application/json

{
  "nome": "Produto1Fisico (PUT)",
  "fabricanteUsername": "Fabrica1",
  "produtoCatalogoId": 1,
  "encomendaId": 1
}

###
DELETE http://localhost:8080/intellipac/api/produtosFisicos/4
Accept: application/json

##### Detalhes de um produtoFisico
GET http://localhost:8080/intellipac/api/produtosFisicos/11
Accept: application/json

##### Fabricantes
GET http://localhost:8080/intellipac/api/fabricantes
Accept: application/json

###
POST http://localhost:8080/intellipac/api/fabricantes
Content-Type: application/json

{
  "nome": "Fabricante (POST)",
  "username": "teste",
  "password": "123",
  "email": "post@mail.pt"
}

###
PUT http://localhost:8080/intellipac/api/fabricantes/teste
Content-Type: application/json

{
  "nome": "Fabricante (PUT)",
  "email": "put@mail.pt"
}

###
DELETE http://localhost:8080/intellipac/api/fabricantes/Fabrica2
Accept: application/json

###
GET http://localhost:8080/intellipac/api/fabricantes/Apple
Accept: application/json

### REQUEST JWT TOKEN
POST http://localhost:8080/intellipac/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Apple",
  "password": "123"
}

### User detail
GET http://localhost:8080/intellipac/api/auth/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJGYWJyaWNhMSIsImlhdCI6MTcwNTI2MDM2NSwiZXhwIjoxNzA1MjYzOTY1fQ._m5zo595ICGOKQdwbAQAy1uf8uQ5G_ckShutvgur4pUkFHUzk_I4Dkd8AT0xx8w4

### GET Operadores de Logistica
GET http://localhost:8080/intellipac/api/operadores
Accept: application/json

### POST Operadores de Logistica
POST http://localhost:8080/intellipac/api/operadores
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJGYWJyaWNhMSIsImlhdCI6MTcwMzUzMjIxNiwiZXhwIjoxNzAzNTM1ODE2fQ.QSN10txLm3lhwXK5HF9_FLFyG-frqurDJ7xfbqrUg6M8WheWC1aETiWNQQys-2kp
Content-Type: application/json

{
  "email": "diogo@mail.com",
  "name": "Diogo Diogo",
  "username": "DiogoGuerra",
  "password": "123"
}

### getOperadoresLogisticaDetails()
GET http://localhost:8080/intellipac/api/operadores/ValterLogo
Accept: application/json

### GET Clientes
GET http://localhost:8080/intellipac/api/clientes
Accept: application/json

### POST Clientes
POST http://localhost:8080/intellipac/api/clientes
Content-Type: application/json

{
  "email": "marco@mail.com",
  "name": "Marcio",
  "username": "Marcyo",
  "password": "123"
}

### getClienteDetails()
GET http://localhost:8080/intellipac/api/clientes/Marcyo
Accept: application/json


### ------------- SENSORES -------------

### GET SENSORES
GET http://localhost:8080/intellipac/api/sensores
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJBcHBsZSIsImlhdCI6MTcwNTY2MDY1NywiZXhwIjoxNzA1NjY0MjU3fQ.3Lq18jEAIzuKJdyTH0tM5gsRFiTemDIk7QqcdZ8KZDc5N7C-UIOziZzQk-vu__u5
Accept: application/json

### GET SENSOR DETAILS
GET http://localhost:8080/intellipac/api/sensores/7
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJBcHBsZSIsImlhdCI6MTcwNTY2MDY1NywiZXhwIjoxNzA1NjY0MjU3fQ.3Lq18jEAIzuKJdyTH0tM5gsRFiTemDIk7QqcdZ8KZDc5N7C-UIOziZzQk-vu__u5
Accept: application/json


### POST SENSORES
POST http://localhost:8080/intellipac/api/sensores
Content-Type: application/json

{
  "tipo": "xpto",
  "unidade": "Celsius"
}

### DELETE SENSORES
DELETE http://localhost:8080/intellipac/api/sensores/6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJBcHBsZSIsImlhdCI6MTcwNTc3MzE0NSwiZXhwIjoxNzA1Nzc2NzQ1fQ.ZKWntVvrcmwLlyNQfJX6mWgFAxzOFuNt09Zg1V1L-h46_FLb7muuJgNZq4JcFmae


### UPDATE SENSORES
PUT http://localhost:8080/intellipac/api/sensores/1
Content-Type: application/json

{
  "idSensor": 20,
  "tipo": "Temperatura",
  "valor": "20",
  "unidade": "CE"
}

### ------------- EMBALAGENS -------------

### GET ALL EMBALAGENS
GET http://localhost:8080/intellipac/api/embalagens
Accept: application/json

### GET EMBALAGEM
GET http://localhost:8080/intellipac/api/embalagens/15
Accept: application/json

### POST EMBALAGEM
POST http://localhost:8080/intellipac/api/embalagens
Content-Type: application/json

{
  "material": "Teste",
  "largura": 10,
  "altura": 10,
  "comprimento": 10
}

### PUT EMBALAGEM
PUT http://localhost:8080/intellipac/api/embalagens/15
Content-Type: application/json

{
  "material": "Borracha",
  "largura": 5,
  "altura": 5,
  "comprimento": 5
}

### GET TIPO EMBALAGEM
GET http://localhost:8080/intellipac/api/tipoEmbalagens
Accept: application/json


### ------------- OBSERVACOES -------------

### GET ALL OBSERVACOES
GET http://localhost:8080/intellipac/api/observacoes
Accept: application/json

### GET OBSERVACAO
GET http://localhost:8080/intellipac/api/observacoes/3
Accept: application/json

### GET OBSERVACOES DE SENSOR
GET http://localhost:8080/intellipac/api/observacoes/sensor/1
Accept: application/json

### GET ULTIMA OBSERVACAO DE SENSOR
GET http://localhost:8080/intellipac/api/observacoes/sensor/1/last
Accept: application/json

### POST OBSERVACAO
POST http://localhost:8080/intellipac/api/observacoes
Content-Type: application/json

{
  "valor": "30",
  "sensorId": 1
}

### DELETE OBSERVACAO
DELETE http://localhost:8080/intellipac/api/observacoes/4
Accept: application/json

### UPDATE OBSERVACAO
PUT http://localhost:8080/intellipac/api/observacoes/1
Content-Type: application/json

{
  "sensorId": 4
}

### ------------- ENCOMENDAS -------------

### GET ALL ENCOMENDAS
GET http://localhost:8080/intellipac/api/encomendas
Accept: application/json

### GET ENCOMENDA
GET http://localhost:8080/intellipac/api/encomendas/1
Accept: application/json

### GET ENCOMENDAS DE CLIENTE
GET http://localhost:8080/intellipac/api/encomendas/username/Marco
Accept: application/json

### POST ENCOMENDA
POST http://localhost:8080/intellipac/api/encomendas
Content-Type: application/json

{
  "consumidorFinal": "Marco",
  "operadorLogistica": "Amazon",
  "produtos": [
    {
      "produtoCatalogoId": 1
    },
    {
      "produtoCatalogoId": 2
    }
  ]
}

### DELETE ENCOMENDA
DELETE http://localhost:8080/intellipac/api/encomendas/4
Accept: application/json

### PATCH ENCOMENDA ESTADO
PATCH http://localhost:8080/intellipac/api/encomendas/2/estado
Content-Type: application/json

{
  "estado": "extraviada"
}


### ------EMBALAGEM DE PRODUTOS------
GET http://localhost:8080/intellipac/api/embalagensDeProduto
Accept: application/json

### Criar Embalagem De Produto
POST http://localhost:8080/intellipac/api/embalagensDeProduto
Content-Type: application/json

{
  "material": "Teste",
  "largura": 10,
  "altura": 10,
  "comprimento": 10,
  "tipoEmbalagem": 3
}

### Update Embalagem De Produto
PUT http://localhost:8080/intellipac/api/embalagensDeProduto/7
Content-Type: application/json

{
  "material": "Borracha",
  "tipoEmbalagem": "2"
}

### Eliminar Embalagem de Produto
DELETE http://localhost:8080/intellipac/api/embalagensDeProduto/8
Content-Type: application/json

### Detalhes de uma embalagem de Produto
GET http://localhost:8080/intellipac/api/embalagensDeProduto/13
Accept: application/json

### ------AUTENTICAÇAO DE UTILIZADOR------
### LOGIN
POST http://localhost:8080/intellipac/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Marco",
  "password": "123"
}

### GET AUTHENTICATED USER
GET http://localhost:8080/intellipac/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJBcHBsZSIsImlhdCI6MTcwNTYyNjAzNCwiZXhwIjoxNzA1NjI5NjM0fQ.OVySgN64OGMC6SJsoTxLSTu4pYwh-WAvy-9QEk2wgGGBTaTilN47JIFZV_eTMmVp


### ------EMBALAGEM DE TRANSPORTE------
GET http://localhost:8080/intellipac/api/embalagensDeTransporte
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJjbyIsImlhdCI6MTcwNTYyNjMzMSwiZXhwIjoxNzA1NjI5OTMxfQ.lcdjIuE_Vj0HAU5zz-RY2arTrDPU3FyAfDLm2HZvsJM6zHJZtPEvLsGHEpdux07H

### Criar Embalagem De Transporte
POST http://localhost:8080/intellipac/api/embalagensDeTransporte
Content-Type: application/json

{
  "material": "Metal",
  "largura": 10,
  "altura": 10,
  "comprimento": 10
}

### POST removerSensor
POST http://localhost:8080/intellipac/api/embalagensDeTransporte/9/removerSensor
Content-Type: application/json

{
  "sensorId": 1
}

### Update Embalagem De Transporte
PUT http://localhost:8080/intellipac/api/embalagensDeTransporte/9
Content-Type: application/json

{
  "material": "Borracha",
  "largura": 10,
  "altura": 10,
  "comprimento": 10
}

### PATCH Embalagem de Transporte ESTADO
PATCH http://localhost:8080/intellipac/api/embalagensDeTransporte/9/estado
Content-Type: application/json

{
  "estado": 1
}

### Eliminar Embalagem de Transporte
DELETE http://localhost:8080/intellipac/api/embalagensDeTransporte/8
Content-Type: application/json

### Detalhes de uma embalagem de Transporte
GET http://localhost:8080/intellipac/api/embalagensDeTransporte/9
Accept: application/json

### ------TESTE DE TIPOSENSOR ------
### Criar produto fisico que tem um sensor "Vento" no tipoSensor do Catalogo associado
POST http://localhost:8080/intellipac/api/produtosFisicos
Content-Type: application/json

{
  "produtoCatalogoId": 1,
  "encomendaId": 1
}

### Get da embalagem desse novo produto
GET http://localhost:8080/intellipac/api/embalagensDeProduto/15
Accept: application/json

### ----TESTE-----
GET http://localhost:8080/intellipac/api/encomendas
Accept: application/json

### Get
GET http://localhost:8080/intellipac/api/encomendas/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJBbWF6b24iLCJpYXQiOjE3MDU2MjQ3MjIsImV4cCI6MTcwNTYyODMyMn0.DWxLq91Jh7lriaJdZ7PTUHRd5YrhGM6shcZRMENG1C8OCY8cYI0Z874fOXv7iGJ1

### GET SENSOR DETAILS
GET http://localhost:8080/intellipac/api/sensores/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJBbWF6b24iLCJpYXQiOjE3MDU2MjQ3MjIsImV4cCI6MTcwNTYyODMyMn0.DWxLq91Jh7lriaJdZ7PTUHRd5YrhGM6shcZRMENG1C8OCY8cYI0Z874fOXv7iGJ1


### Update estado encomenda
PATCH http://localhost:8080/intellipac/api/encomendas/1/estado
Content-Type: application/json

{
  "estado": "ENTREGUE"
}

### GET SENSOR DETAILS
GET http://localhost:8080/intellipac/api/sensores/1
Accept: application/json

### GET PRODUTOS CATALOGO FROM FABRICANTE
GET http://localhost:8080/intellipac/api/produtosCatalogo/fabricante/Nacional
Accept: application/json