##### ProdutosCatalogo
GET http://localhost:8080/intellipac/api/produtosCatalogo
Accept: application/json
###
POST http://localhost:8080/intellipac/api/produtosCatalogo
Content-Type: application/json

{
  "nome": "Produto (POST)",
  "fabricanteUsername": "Fabrica1"

}
###
PUT http://localhost:8080/intellipac/api/produtosCatalogo/2
Content-Type: application/json

{
  "nome": "Produto (PUT)",
  "fabricanteUsername": "Fabrica1"
}

###
DELETE http://localhost:8080/intellipac/api/produtosCatalogo/2
Accept: application/json

##### Detalhes de um produtoCataloo
GET http://localhost:8080/intellipac/api/produtosCatalogo/1
Accept: application/json

##### Produtos Fisicos

GET http://localhost:8080/intellipac/api/produtosFisicos
Accept: application/json
###
POST http://localhost:8080/intellipac/api/produtosFisicos
Content-Type: application/json

{
  "nome": "Produto1Fisico (POST)",
  "fabricanteUsername": "Fabrica1",
  "produtoCatalogoId" : 1,
  "encomendaId" : 1

}
###
PUT http://localhost:8080/intellipac/api/produtosFisicos/3
Content-Type: application/json

{
  "nome": "Produto1Fisico (PUT)",
  "fabricanteUsername": "Fabrica1",
  "produtoCatalogoId" : 1,
  "encomendaId" : 1
}
###
DELETE http://localhost:8080/intellipac/api/produtosFisicos/4
Accept: application/json

##### Detalhes de um produtoFisico
GET http://localhost:8080/intellipac/api/produtosFisicos/3
Accept: application/json
##### Fabricantes
GET http://localhost:8080/intellipac/api/fabricantes
Accept: application/json

###
POST http://localhost:8080/intellipac/api/fabricantes
Content-Type: application/json

{
  "nomeFabricante": "Fabricante (POST)"
}

###
PUT http://localhost:8080/intellipac/api/fabricantes/3
Content-Type: application/json

{
  "nomeFabricante": "Fabricante (PUT)"
}

###
DELETE http://localhost:8080/intellipac/api/fabricantes/3
Accept: application/json

###
GET http://localhost:8080/intellipac/api/fabricantes/1
Accept: application/json

### REQUEST JWT TOKEN
POST http://localhost:8080/intellipac/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Fabrica1", "password": "123" }


### GET Operadores de Logistica
GET http://localhost:8080/intellipac/api/operadores
Accept: application/json

### POST Operadores de Logistica
POST http://localhost:8080/intellipac/api/operadores
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJGYWJyaWNhMSIsImlhdCI6MTcwMzUzMjIxNiwiZXhwIjoxNzAzNTM1ODE2fQ.QSN10txLm3lhwXK5HF9_FLFyG-frqurDJ7xfbqrUg6M8WheWC1aETiWNQQys-2kp
Content-Type: application/json

{
 "email": "diogo@mail.com",
 "name": "Diogo Diogo",
 "username": "DiogoGuerra",
 "password": "123"
}

### getOperadoresLogisticaDetails()
GET http://localhost:8080/intellipac/api/operadores/ValterLogo
Accept: application/json

### GET Clientes
GET http://localhost:8080/intellipac/api/clientes
Accept: application/json

### POST Clientes
POST http://localhost:8080/intellipac/api/clientes
Content-Type: application/json

{
  "email": "marco@mail.com",
  "name": "Marcio",
  "username": "Marcyo",
  "password": "123"
}

### getClienteDetails()
GET http://localhost:8080/intellipac/api/clientes/Marcyo
Accept: application/json


### ------------- SENSORES -------------

### GET SENSORES
GET http://localhost:8080/intellipac/api/sensores
Accept: application/json

### GET SENSOR DETAILS
GET http://localhost:8080/intellipac/api/sensores/1
Accept: application/json

### POST SENSORES
POST http://localhost:8080/intellipac/api/sensores
Content-Type: application/json

{
  "idSensor": 8,
  "tipo": "Temperatura",
  "unidade": "Celsius"
}

### DELETE SENSORES
DELETE http://localhost:8080/intellipac/api/sensores/8
Accept: application/json

### UPDATE SENSORES
PUT http://localhost:8080/intellipac/api/sensores/1
Content-Type: application/json

{
  "idSensor": 20,
  "tipo": "Temperatura",
  "valor": "20",
  "unidade": "CE"
}

### ------------- EMBALAGENS -------------

### GET ALL EMBALAGENS
GET http://localhost:8080/intellipac/api/embalagens
Accept: application/json

### GET EMBALAGEM
GET http://localhost:8080/intellipac/api/embalagens/1
Accept: application/json



### ------------- OBSERVACOES -------------

### GET ALL OBSERVACOES
GET http://localhost:8080/intellipac/api/observacoes
Accept: application/json

### GET OBSERVACAO
GET http://localhost:8080/intellipac/api/observacoes/3
Accept: application/json

### GET OBSERVACOES DE SENSOR
GET http://localhost:8080/intellipac/api/observacoes/sensor/1
Accept: application/json

### GET ULTIMA OBSERVACAO DE SENSOR
GET http://localhost:8080/intellipac/api/observacoes/sensor/1/last
Accept: application/json

### POST OBSERVACAO
POST http://localhost:8080/intellipac/api/observacoes
Content-Type: application/json

{
  "valor": "30",
  "sensorId": 1
}

### DELETE OBSERVACAO
DELETE http://localhost:8080/intellipac/api/observacoes/4
Accept: application/json

### UPDATE OBSERVACAO
PUT http://localhost:8080/intellipac/api/observacoes/1
Content-Type: application/json

{
  "sensorId": 4
}

### ------------- ENCOMENDAS -------------

### GET ALL ENCOMENDAS
GET http://localhost:8080/intellipac/api/encomendas
Accept: application/json

### GET ENCOMENDA
GET http://localhost:8080/intellipac/api/encomendas/1
Accept: application/json

### POST ENCOMENDA
POST http://localhost:8080/intellipac/api/encomendas
Content-Type: application/json

{
  "consumidorFinal": "Marco",
  "operadorLogistica": "Joaoz",
  "produtos": []
}

### DELETE ENCOMENDA
DELETE http://localhost:8080/intellipac/api/encomendas/4
Accept: application/json

### PATCH ENCOMENDA ESTADO
PATCH http://localhost:8080/intellipac/api/encomendas/2/estado
Content-Type: application/json

{
  "estado": "extraviada"
}


### ------EMBALAGEM DE PRODUTOS------
GET http://localhost:8080/intellipac/api/embalagensDeProduto
Accept: application/json

### Criar Embalagem De Produto
POST http://localhost:8080/intellipac/api/embalagensDeProduto
Content-Type: application/json

{
  "material" : "Plastico",
  "tipoEmbalagem" : "3"
}

### Update Embalagem De Produto
PUT http://localhost:8080/intellipac/api/embalagensDeProduto/7
Content-Type: application/json

{
  "material" : "Borracha",
  "tipoEmbalagem" : "2"
}

### Eliminar Embalagem de Produto
DELETE http://localhost:8080/intellipac/api/embalagensDeProduto/8
Content-Type: application/json

### Detalhes de uma embalagem de Produto
GET http://localhost:8080/intellipac/api/embalagensDeProduto/5
Accept: application/json

### ------AUTENTICAÇAO DE UTILIZADOR------
### LOGIN
POST http://localhost:8080/intellipac/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Marco", "password": "123" }

### GET AUTHENTICATED USER
GET http://localhost:8080/intellipac/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJjbyIsImlhdCI6MTcwNTE3NjA3OSwiZXhwIjoxNzA1MTc5Njc5fQ._YgxFAMeKFUsCNBxQB0JfcfVBQq6aTX9hcJVL6Z9dn9ezoSp9s521K5e1q5h7ZmW


### ------EMBALAGEM DE TRANSPORTE------
GET http://localhost:8080/intellipac/api/embalagensDeTransporte
Accept: application/json

### Criar Embalagem De Transporte
POST http://localhost:8080/intellipac/api/embalagensDeTransporte
Content-Type: application/json

{
  "material" : "Metal"
}

### Update Embalagem De Transporte
PUT http://localhost:8080/intellipac/api/embalagensDeTransporte/7
Content-Type: application/json

{
  "material" : "Borracha"
}

### Eliminar Embalagem de Transporte
DELETE http://localhost:8080/intellipac/api/embalagensDeTransporte/8
Content-Type: application/json

### Detalhes de uma embalagem de Transporte
GET http://localhost:8080/intellipac/api/embalagensDeTransporte/7
Accept: application/json