##### ProdutosCatalogo
GET http://localhost:8080/intellipac/api/produtosCatalogo
Accept: application/json
###
POST http://localhost:8080/intellipac/api/produtosCatalogo
Content-Type: application/json

{
  "nome": "Produto (POST)",
  "fabricanteUsername": "Fabrica1"

}
###
PUT http://localhost:8080/intellipac/api/produtosCatalogo/2
Content-Type: application/json

{
  "nome": "Produto (PUT)",
  "fabricanteUsername": "Fabrica1"
}

###
DELETE http://localhost:8080/intellipac/api/produtosCatalogo/2
Accept: application/json

##### Detalhes de um produtoCataloo
GET http://localhost:8080/intellipac/api/produtosCatalogo/1
Accept: application/json

##### Fabricantes
GET http://localhost:8080/intellipac/api/fabricantes
Accept: application/json

###
POST http://localhost:8080/intellipac/api/fabricantes
Content-Type: application/json

{
  "nomeFabricante": "Fabricante (POST)"
}

###
PUT http://localhost:8080/intellipac/api/fabricantes/3
Content-Type: application/json

{
  "nomeFabricante": "Fabricante (PUT)"
}

###
DELETE http://localhost:8080/intellipac/api/fabricantes/3
Accept: application/json

###
GET http://localhost:8080/intellipac/api/fabricantes/1
Accept: application/json

### REQUEST JWT TOKEN
POST http://localhost:8080/intellipac/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Fabrica1", "password": "123" }


### GET Operadores de Logistica
GET http://localhost:8080/intellipac/api/operadores
Accept: application/json

### POST Operadores de Logistica
POST http://localhost:8080/intellipac/api/operadores
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJGYWJyaWNhMSIsImlhdCI6MTcwMzUzMjIxNiwiZXhwIjoxNzAzNTM1ODE2fQ.QSN10txLm3lhwXK5HF9_FLFyG-frqurDJ7xfbqrUg6M8WheWC1aETiWNQQys-2kp
Content-Type: application/json

{
 "email": "diogo@mail.com",
 "name": "Diogo Diogo",
 "username": "DiogoGuerra",
 "password": "123"
}

### getOperadoresLogisticaDetails()
GET http://localhost:8080/intellipac/api/operadores/ValterLogo
Accept: application/json

### GET Clientes
GET http://localhost:8080/intellipac/api/clientes
Accept: application/json

### POST Clientes
POST http://localhost:8080/intellipac/api/clientes
Content-Type: application/json

{
  "email": "marco@mail.com",
  "name": "Marcio",
  "username": "Marcyo",
  "password": "123"
}

### getClienteDetails()
GET http://localhost:8080/intellipac/api/clientes/Marcyo
Accept: application/json


### GET SENSORES
GET http://localhost:8080/intellipac/api/sensores
Accept: application/json

### POST SENSORES
POST http://localhost:8080/intellipac/api/sensores
Content-Type: application/json

{
  "idSensor": 8,
  "tipo": "Temperatura",
  "valor": "20",
  "unidade": "Celsius"
}

### DELETE SENSORES
DELETE http://localhost:8080/intellipac/api/sensores/8
Accept: application/json

### UPDATE SENSORES
PUT http://localhost:8080/intellipac/api/sensores/1
Content-Type: application/json

{
  "idSensor": 20,
  "tipo": "Temperatura",
  "valor": "20",
  "unidade": "CE"
}

### GET SENSORES BY ID
GET http://localhost:8080/intellipac/api/sensores/1
Accept: application/json

## OBSERVACOES

### GET ALL OBSERVACOES
GET http://localhost:8080/intellipac/api/observacoes
Accept: application/json
